language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "node"

services:
  - mongodb

install:
  - npm install
  - npm install -g codecov istanbul

script:
  - npm run lint
  - npm run build:production
  - npm run codecov && codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

cache:
  directories:
    - node_modules
